[workspace]
members = [
    "core",
    "examples/api_guide",
    "examples/middleware_guide", 
    "examples/database_example",
    "examples/article_system_example",
]
resolver = "2"

# 根目录不再是一个包，而是一个 workspace