[workspace]
members = [
    "core",
    "examples/api_example",
    "examples/middleware_example", 
    "examples/database_example",
    "examples/article_system_example",
    "examples/chain_example",
    "examples/custom_response_example",
    "examples/swagger_example",
]
resolver = "2"

# 根目录不再是一个包，而是一个 workspace