[package]
name = "ree"
version = "0.1.0"
edition = "2024"
description = "A simple HTTP framework for Rust"
license = "MIT"


[dependencies]
hyper = { version = "1.6.0", features = ["full"] }
tokio = { version = "1.45.1", features = ["full"] }
http-body-util = "0.1.3"
hyper-util = { version = "0.1.14", features = ["full"] }
async-trait = "0.1.88"
